### ISSUE TITLE
Tls cert renewed automaticaly?

### ISSUE THREAD

**Issue by joliejuke-orga** [mlerczak/haproxy-letsencrypt#5]
Hi,

I see that you forked BradJones docker repository: 
https://github.com/BradJonesLLC/docker-haproxy-letsencrypt

In this repository, certs are not automatically renewed.
Did you implemented this feature?

Best.

**Comment by mlerczak** [comment]
Hi, there is no auto renew.
You can add to crontab script to renew or run it manually. 


Run to generate / renew certs.
`generateCertsForHAProxy`

There is also second script but only forked not tested, always use first option.
`renewCertsForHAProxy`
